# 設定の参考
# https://qiita.com/ayatothos/items/5dd5d2d09bfd52e06a6b

# テーマは以下から選べる
# https://qiita.com/aKuad/items/c81019003ce669c17df0
theme: jekyll-theme-minimal
logo: assets/img/logo.png
favicon_ico: assets/img/logo.png
title: serna37's Library
description: C++ アルゴリズムとデータ構造のライブラリ
exclude: ['bits', 'bundler']

