# 設定の参考
# https://qiita.com/ayatothos/items/5dd5d2d09bfd52e06a6b

# テーマは以下から選べる
# https://qiita.com/aKuad/items/c81019003ce669c17df0

baseurl: "/library-cpp"
theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/serna37/library-cpp/refs/heads/main/.verify-helper/docs/assets/images/serna37.jpg
title: serna37's Library
description: C++ アルゴリズムとデータ構造のライブラリ
exclude: ['bits', 'bundler']
email: 37serna37serna37serna@gmial.com
author: serna37  
