description: "C++ \u30A2\u30EB\u30B4\u30EA\u30BA\u30E0\u3068\u30C7\u30FC\u30BF\u69CB\
  \u9020\u306E\u30E9\u30A4\u30D6\u30E9\u30EA"
exclude:
- bits
- bundler
logo: https://serna37.github.io/library-cpp/assets/img/logo.png
plugins:
- jemoji
- jekyll-redirect-from
theme: jekyll-theme-minimal
title: serna37's Library
