description: Jekyll theme with One Dark colors
highlighter: rouge
markdown: kramdown
plugins:
- jemoji
- jekyll-redirect-from
remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-theme-minimal
title: My One Dark Blog
