description: "C++\u7AF6\u30D7\u30ED\u5411\u3051 \u30A2\u30EB\u30B4\u30EA\u30BA\u30E0\
  \u3068\u30C7\u30FC\u30BF\u69CB\u9020\u306E\u30E9\u30A4\u30D6\u30E9\u30EA"
plugins:
- jemoji
- jekyll-redirect-from
theme: jekyll-theme-cayman
title: serna37's Library
