name: modify default html

on:
  push:
    branches:
      - gh-pages
    paths-ignore:
      - 'default.html' # 自身による変更でのループ防止（念のため）

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0 # 全履歴を取得（oj-verifyの「最終更新日」判定に必要）

      - name: Get file from main branch
        run: |
          git checkout origin/main -- .verify-helper/docs/default.html

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --exit-code; then
            git add .verify-helper/docs/default.html
            git commit -m "chore: sync file from main [skip ci]"
            git push origin gh-pages
          else
            echo "No changes to sync."
          fi
